# This is a basic workflow to help you get started with Actions

name: Anki
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest # Don't care about the runner version but it's required
    container:
      image: ubuntu:20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Bootstrap installer dependencies
        run: |
          apt-get update && \
          apt-get --assume-yes install \
          sudo \
          curl \
          jq \
          xdg-utils

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Anki
        shell: bash # Avoids "Illegal option -o pipefail"
        run: ./scripts/programs/anki.bash

      # The version option requires an ignored argument.
      - name: Test Anki version
        run: /usr/local/bin/anki --version 1
