name: Azure Devops CLI

on:
  # Disabled until the following issue is resolved.
  # https://github.com/Azure/azure-devops-cli-extension/issues/1272
  # "az devops login: Pip failed with status code 2 for package keyring~=17.1.1"
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash

      - name: Install Azure Devops CLI
        shell: su norm --command "bash --login {0}"
        run: programs/az/install.bash

      - name: Install Azure Devops CLI again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/az/install.bash
