name: Bashmarks
on:
  push:
    paths:
      - programs/bashmarks/install.bash
      - .github/workflows/Bashmarks.yml

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      matrix:
        os:
          - "ubuntu:20.04"
          - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Bashmarks
        shell: su norm --command "bash --login {0}"
        run: programs/bashmarks/install.bash

      - name: Install Bashmarks again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/bashmarks/install.bash
