name: DVC (Data Version Control)
on:
  push:
    paths:
      - programs/dvc/install.bash
      - .github/workflows/DVC (Data Version Control).yml
  schedule:
    # Not at the start of an hour or a day to decreate the chance of delay.
    # See schedule documentation.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "17 5 * * *"

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu:20.04"
          - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1

      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install DVC (Data Version Control)
        shell: su norm --command "bash --login {0}"
        run: programs/dvc/install.bash

      - name: Install DVC (Data Version Control) again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/dvc/install.bash
