name: git-secrets
on:
  push:
    branches: [ master ]
      paths:
        - programs/git-secrets/install.bash

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      matrix:
        os:
          - "ubuntu:20.04"
          - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-secrets
        shell: su norm --command "bash --login {0}"
        run: programs/git-secrets/install.bash

      - name: Install git-secrets again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/git-secrets/install.bash
