name: git-secrets
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install sudo
        run: |
          apt-get update && \
          apt-get --assume-yes install \
          sudo

      - name: Install git-secrets
        shell: bash # Avoids "Illegal option -o pipefail"
        run: ./scripts/programs/git-secrets.bash
