name: GnuCash 4
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      matrix:
        os:
          - "ubuntu:20.04"
          # GnuCash 4.8 is in the Ubuntu 22 repository.
          # https://launchpad.net/ubuntu/jammy/+source/gnucash
          # - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash

      - name: Install GnuCash 4
        shell: su norm --command "bash --login {0}"
        run: programs/gnucash4/install.bash

      - name: Install GnuCash 4 again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/gnucash4/install.bash
