# This is a basic workflow to help you get started with Actions

name: Pipelines CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest # Don't care about the runner version but it's required
    container:
      image: ubuntu:20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install sudo
        run: apt-get update && apt-get install sudo

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install pipelines CLI
        run: ./scripts/programs/pipelines.sh
