name: Pre-commit checks
on:
  push:
  workflow_dispatch:

jobs:
  run_pre_commit_checks:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - run: python3 -m pip install pipx

      - run: python3 -m pipx install poetry
