name: Pre-commit
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre_commit:
    name: Run hooks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Run hooks
        run: pre-commit run --all-files
