name: Rain
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      matrix:
        os:
          - "ubuntu:20.04"
          - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check GitHub API limit
        run: |
          apt-get update && apt-get install -y curl

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/rate_limit

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rain
        shell: su norm --command "bash --login {0}"
        run: programs/rain/install.bash

      - name: Install Rain again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/rain/install.bash
