# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest # Don't care about the runner version but it's required
    container:
      image: ubuntu:20.04
    defaults:
      run:
        # Fake bash's interactive mode, which loads ~/.bashrc.
        shell: bash -c "BASH_ENV=~/.bashrc bash {0}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # sudo is invoked by the install script.
      - name: Install sudo
        run: apt-get update && apt-get --assume-yes install sudo

      - name: Set up BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v2

        # bats-assert depends on bats-support
        # wget ships with desktop Ubuntu
        # unzip ships with desktop Ubuntu
      - name: Add bats-assert
        run: |
          apt-get install --assume-yes wget unzip
          
          wget https://github.com/bats-core/bats-assert/archive/master.zip -O assert.zip
          unzip assert.zip
          mv bats-assert-master/ bats-assert/
          
          wget https://github.com/bats-core/bats-support/archive/master.zip -O support.zip
          unzip support.zip
          mv bats-support-master/ bats-support/

      - name: Run install script
        run: |
          cd scripts
          ./install.sh

      # In a real interactive session the PATH is set automatically in the
      # expected way by sourcing bashrc. But Github Actions requires this
      # syntax, and it takes effect only on subsequent steps. 
      - name: Set PATH the Github way
        run: |
          echo "~/.local/bin" >> "${GITHUB_PATH}"

      - name: Debug PATH
        run: echo $PATH

      - name: Test
        run: |
          bats --tap test.bats

