name: Test changed installers
on:
  push:

permissions:
  contents: read

jobs:
  pre_commit:
    name: Pre-commit
    uses: ./.github/workflows/pre-commit.yml

  list_installers:
    name: List changed installers
    runs-on: ubuntu-latest
    outputs:
      installers: ${{steps.installers.outputs.all_changed_files}}
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get changed installers
        id: installers
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          path: programs
          dir_names: true
          dir_names_max_depth: 1
          matrix: true

  test_installers:
    name: Test installers
    needs: [pre_commit, list_installers]
    if: success() && needs.list_installers.outputs.installers != '[]'
    uses: ./.github/workflows/test_installers.yml
    with:
      installers: ${{needs.list_installers.outputs.installers}}
