name: Test all installers
on:
  schedule:
    # To decrease the chance of delay, avoid the start of the hour.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "17 5 * * *"
  workflow_dispatch:

jobs:
  list_installers:
    name: List all installers
    runs-on: ubuntu-latest
    outputs:
      installers: ${{steps.list_step.outputs.installers}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List installers
        id: list_step
        run: |
          {
            printf "installers="
            find programs -mindepth 1 -maxdepth 1 -printf "%P\n" \
            | sort | jq -R | jq -s -c -M
          } >> "$GITHUB_OUTPUT"

  test_installers:
    name: Test installers
    needs: list_installers
    uses: ./.github/workflows/test_installers.yml
    with:
      installers: ${{needs.list_installers.outputs.installers}}
