# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest # Don't care about the runner version but it's required
    container: ubuntu:20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install sudo
        run: apt-get update && apt-get --assume-yes install sudo

      - name: Set up BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run installer
        run: |
          cd scripts
          ./install.sh

      - name: Set PATH the Github way
        run: echo "~/.local/bin" >> $GITHUB_PATH
      
      - name: Desperately test sanity
        run: |
          echo ~/.bashrc
          cat ~/.bashrc
          echo $PATH
          source ~/.bashrc
          echo $PATH

      - name: Test
        shell: bash -leo pipefail {0}
        run: |
          echo "PATH=$PATH"
          bats --tap test.bats

defaults:
  run:
    shell: bash -leo pipefail {0}
