# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest # Don't care about the runner version but it's required
    container:
      image: ubuntu:20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install sudo
        run: apt-get update && apt-get --assume-yes install sudo

      - name: Set up BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v2

      # Brew refuses to install as root.
      # The Docker image has only a root user.
      # https://askubuntu.com/questions/716174/dont-run-this-as-root-docker-image
      # https://www.yegor256.com/2014/08/29/docker-non-root.html
      - name: Create non-root user
        run: |
          # https://www.yegor256.com/2014/08/29/docker-non-root.html
          adduser --disabled-password --gecos '' r
          adduser r sudo
          echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

      - name: Run install script
        run: |
          cd scripts
          su r -c ./install.sh

        # Loading .bashrc should just take care of this automatically, but
        # I can't find anyway to set PATH directly from the install script.
        # I think it's because of CVE-2020-15228.
        # https://github.com/advisories/GHSA-mfwh-5m23-j46w
        # So I rewrote the script with its paths in a file to make this easier.
      - name: Set the PATH the Github way
        run: |
          cat ./scripts/.pathfile |
          while read p; do eval echo $p; done |
          tr '\n' ':' \
          > $GITHUB_PATH

      - name: Test
        run: |
          su r -c bats --tap test.bats

defaults:
  run:
    shell: bash -leo pipefail {0}
