name: Typora
on:
  push:
    paths:
      - programs/typora/install.bash
      - .github/workflows/Typora.yml
  schedule:
    # Not at the start of an hour or a day to decreate the chance of delay.
    # See schedule documentation.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "17 5 * * *"

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu:20.04"
          - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix flaky networking in GitHub Actions
        run: |
            sudo apt install ethtool
            sudo ethtool -K eth0 tx off rx off

      - name: Install Typora
        shell: su norm --command "bash --login {0}"
        run: programs/typora/install.bash

      - name: Install Typora again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/typora/install.bash
