name: Visual Studio Code
on:
  push:
    paths:
      - programs/vscode/install.bash
      - .github/workflows/Visual Studio Code.yml

  workflow_dispatch:

jobs:
  test_idempotent_installation:

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu:20.04"
          - "ubuntu:22.04"

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os }}"

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare Docker
        run: ./scripts/prepare_docker.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Visual Studio Code
        shell: su norm --command "bash --login {0}"
        run: programs/vscode/install.bash

      - name: Install Visual Studio Code again (test idempotency)
        shell: su norm --command "bash --login {0}"
        run: programs/vscode/install.bash
